from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
    ActiveUserListView,
    BreakOpportunityViewSet,
    BreakRecoveryViewSet,
    CurrentUserView,
    DailyPlanBlockViewSet,
    DowntimeEventViewSet,
    HourlyLineUpdateViewSet,
    NotificationInboxView,
    NotificationReadView,
    ObservabilitySummaryView,
    OperationalEscalationViewSet,
    OperationalEventViewSet,
    OperationsDashboardView,
    PilotFeedbackViewSet,
    PilotObservationViewSet,
    PilotStatusView,
    PilotTrialViewSet,
    ProductionAssetViewSet,
    ProductionLineViewSet,
    ProductMaterialReadinessViewSet,
    QualityIncidentViewSet,
    ShiftHandoverViewSet,
    ShiftViewSet,
    SupportCompanionView,
    TeamLeaderAssignmentViewSet,
    WorkspaceRoleView,
)

router = DefaultRouter()
router.register(
    "production-assets",
    ProductionAssetViewSet,
    basename="production-asset",
)
router.register(
    "production-lines",
    ProductionLineViewSet,
    basename="production-line",
)
router.register(
    "shifts",
    ShiftViewSet,
    basename="shift",
)
router.register(
    "downtime-events",
    DowntimeEventViewSet,
    basename="downtime-event",
)
router.register(
    "quality-incidents",
    QualityIncidentViewSet,
    basename="quality-incident",
)
router.register(
    "team-leader-assignments",
    TeamLeaderAssignmentViewSet,
    basename="team-leader-assignment",
)
router.register(
    "hourly-line-updates",
    HourlyLineUpdateViewSet,
    basename="hourly-line-update",
)
router.register(
    "product-material-readiness",
    ProductMaterialReadinessViewSet,
    basename="product-material-readiness",
)
router.register(
    "operational-escalations",
    OperationalEscalationViewSet,
    basename="operational-escalation",
)
router.register(
    "operational-events",
    OperationalEventViewSet,
    basename="operational-event",
)
router.register(
    "shift-handovers",
    ShiftHandoverViewSet,
    basename="shift-handover",
)
router.register(
    "daily-plan-blocks",
    DailyPlanBlockViewSet,
    basename="daily-plan-block",
)
router.register(
    "break-opportunities",
    BreakOpportunityViewSet,
    basename="break-opportunity",
)
router.register(
    "break-recoveries",
    BreakRecoveryViewSet,
    basename="break-recovery",
)
router.register(
    "pilot-trials",
    PilotTrialViewSet,
    basename="pilot-trial",
)
router.register(
    "pilot-observations",
    PilotObservationViewSet,
    basename="pilot-observation",
)
router.register(
    "pilot-feedback",
    PilotFeedbackViewSet,
    basename="pilot-feedback",
)

urlpatterns = [
    path(
        "auth/me/",
        CurrentUserView.as_view(),
        name="current-user",
    ),
    path(
        "active-users/",
        ActiveUserListView.as_view(),
        name="active-user-list",
    ),
    path(
        "dashboard/summary/",
        OperationsDashboardView.as_view(),
        name="operations-dashboard",
    ),
    path(
        "support/companion/",
        SupportCompanionView.as_view(),
        name="support-companion",
    ),
    path(
        "notifications/",
        NotificationInboxView.as_view(),
        name="notification-inbox",
    ),
    path(
        "notifications/<int:event_id>/read/",
        NotificationReadView.as_view(),
        name="notification-read",
    ),
    path(
        "pilot/status/",
        PilotStatusView.as_view(),
        name="pilot-status",
    ),
    path(
        "observability/summary/",
        ObservabilitySummaryView.as_view(),
        name="observability-summary",
    ),
    path(
        "workspace-roles/",
        WorkspaceRoleView.as_view(),
        name="workspace-roles",
    ),
]

urlpatterns += router.urls
