# Generated by Django 5.2.17 on 2026-08-19 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('target_units_per_hour', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('planned_output', models.PositiveIntegerField(default=0)),
                ('actual_output', models.PositiveIntegerField(default=0)),
                ('downtime_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='operations.productionline')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'production_line'],
            },
        ),
        migrations.CreateModel(
            name='QualityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('product', 'Product Quality'), ('packaging', 'Packaging'), ('hygiene', 'Hygiene'), ('equipment', 'Equipment'), ('safety', 'Safety'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_quality_incidents', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_incidents', to='operations.shift')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('production_line', 'date', 'shift_type'), name='unique_line_date_shift'),
        ),
        migrations.AddIndex(
            model_name='qualityincident',
            index=models.Index(fields=['status', 'severity'], name='operations__status_43bd83_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityincident',
            index=models.Index(fields=['occurred_at'], name='operations__occurre_4c418e_idx'),
        ),
    ]
