# Generated by Django 5.2.17 on 2026-08-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_align_core_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_leader_assignments', to=settings.AUTH_USER_MODEL)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_leader_assignments', to='operations.productionline')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_leader_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'shift_type', 'production_line__code'],
                'indexes': [models.Index(fields=['team_leader', 'date', 'shift_type'], name='operations__team_le_765a6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('production_line', 'date', 'shift_type'), name='unique_line_date_shift_assignment')],
            },
        ),
    ]
