# Generated by Django 5.2.17 on 2026-08-26 15:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_add_team_leader_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyLineUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('current_product', models.CharField(blank=True, max_length=150)),
                ('issue_summary', models.CharField(blank=True, max_length=255)),
                ('action_taken', models.TextField(blank=True)),
                ('support_required', models.TextField(blank=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_update_due_at', models.DateTimeField()),
                ('action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_line_update_actions', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hourly_updates', to='operations.teamleaderassignment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_line_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['assignment', 'recorded_at'], name='operations__assignm_5ae8be_idx'), models.Index(fields=['status', 'recorded_at'], name='operations__status_64c1bb_idx')],
            },
        ),
    ]
