# Generated by Django 5.2.17 on 2026-08-29 04:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_add_hourly_line_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=150)),
                ('planned_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_process', 'In Process'), ('short', 'Short'), ('held', 'Held')], default='ready', max_length=20)),
                ('shortage_quantity', models.PositiveIntegerField(default=0)),
                ('expected_available_at', models.DateTimeField(blank=True, null=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_material_readiness', to='operations.teamleaderassignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_material_readiness_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_material_readiness_items', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_material_readiness_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assignment__date', 'assignment__shift_type', 'assignment__production_line__code', 'sequence_number'],
                'indexes': [models.Index(fields=['assignment', 'sequence_number'], name='operations__assignm_c7ecd0_idx'), models.Index(fields=['status', 'expected_available_at'], name='operations__status_c40223_idx'), models.Index(fields=['owner', 'status'], name='operations__owner_i_e7639a_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'sequence_number'), name='unique_assignment_product_sequence')],
            },
        ),
    ]
