# Generated by Django 5.2.17 on 2026-08-30 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_add_product_material_readiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('material', 'Material'), ('quality', 'Quality'), ('staffing', 'Staffing'), ('safety', 'Safety'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('immediate_action', models.TextField(blank=True)),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_due_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_operational_escalations', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_escalations', to='operations.teamleaderassignment')),
                ('hourly_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_escalations', to='operations.hourlylineupdate')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_operational_escalations', to=settings.AUTH_USER_MODEL)),
                ('quality_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_escalations', to='operations.qualityincident')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_operational_escalations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_operational_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'response_due_at', '-raised_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'response_due_at'], name='operations__status_af5a32_idx'), models.Index(fields=['assignment', 'status'], name='operations__assignm_c3f1f4_idx'), models.Index(fields=['owner', 'status'], name='operations__owner_i_04f37f_idx')],
            },
        ),
    ]
