# Generated by Django 5.2.17 on 2026-08-30 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_add_operational_escalations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('operational_summary', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('handed_over_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_shift_handovers', to=settings.AUTH_USER_MODEL)),
                ('escalations', models.ManyToManyField(blank=True, related_name='shift_handovers', to='operations.operationalescalation')),
                ('handed_over_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shift_handovers', to=settings.AUTH_USER_MODEL)),
                ('incoming_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_shift_handovers', to='operations.teamleaderassignment')),
                ('outgoing_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_shift_handovers', to='operations.teamleaderassignment')),
            ],
            options={
                'ordering': ['status', '-handed_over_at'],
                'indexes': [models.Index(fields=['status', 'handed_over_at'], name='operations__status_e96f79_idx'), models.Index(fields=['incoming_assignment', 'status'], name='operations__incomin_1c7e8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('outgoing_assignment', 'incoming_assignment'), name='unique_assignment_shift_handover')],
            },
        ),
    ]
