# Generated by Django 5.2.17 on 2026-08-30 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_add_shift_handovers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('coverage_accepted', 'Coverage Accepted'), ('active', 'Active'), ('recovered', 'Recovered'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_start_at', models.DateTimeField()),
                ('expected_return_at', models.DateTimeField()),
                ('coverage_notes', models.TextField(blank=True)),
                ('coverage_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_recoveries', to='operations.teamleaderassignment')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_break_recoveries', to=settings.AUTH_USER_MODEL)),
                ('cover_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covered_break_recoveries', to=settings.AUTH_USER_MODEL)),
                ('coverage_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_break_coverages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_break_recoveries', to=settings.AUTH_USER_MODEL)),
                ('recovered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_break_recoveries', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_break_recoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'planned_start_at'],
                'indexes': [models.Index(fields=['status', 'expected_return_at'], name='operations__status_5dba34_idx'), models.Index(fields=['cover_user', 'status'], name='operations__cover_u_b2b65a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('planned', 'coverage_accepted', 'active'))), fields=('assignment',), name='unique_open_break_recovery_assignment')],
            },
        ),
    ]
