# Generated by Django 5.2.17 on 2026-09-01 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_add_break_recovery_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.PositiveBigIntegerField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_operational_events', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='operations.teamleaderassignment')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_events', to='operations.productionline')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OperationalEventAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_links', to='operations.operationalevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_event_audience_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operationalevent',
            name='audiences',
            field=models.ManyToManyField(related_name='visible_operational_events', through='operations.OperationalEventAudience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IdempotentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='operations__created_d0fcbc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_user_idempotency_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='operationaleventaudience',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_operational_event_audience'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='operations__event_t_35c969_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['assignment', 'id'], name='operations__assignm_c1b28f_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['production_line', 'id'], name='operations__product_de4361_idx'),
        ),
    ]
