# Generated by Django 5.2.17 on 2026-09-01 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_operationalevent_operationaleventaudience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalescalation',
            name='estimated_lost_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operationalescalation',
            name='loss_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('printer', 'Printer'), ('filler', 'Filler'), ('packer', 'Packer'), ('conveyor', 'Conveyor'), ('labeler', 'Labeler'), ('other', 'Other')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('commissioned_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='operations.productionline')),
            ],
            options={
                'ordering': ('production_line__code', 'code'),
            },
        ),
        migrations.AddField(
            model_name='operationalescalation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_escalations', to='operations.productionasset'),
        ),
        migrations.AddIndex(
            model_name='productionasset',
            index=models.Index(fields=['production_line', 'status'], name='operations__product_87d150_idx'),
        ),
        migrations.AddIndex(
            model_name='productionasset',
            index=models.Index(fields=['asset_type', 'status'], name='operations__asset_t_a56aa9_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionasset',
            constraint=models.UniqueConstraint(fields=('production_line', 'code'), name='unique_asset_code_per_line'),
        ),
    ]
