# Generated by Django 5.2.17 on 2026-09-10 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_pending_pilot_approvals(apps, schema_editor):
    PilotApproval = apps.get_model("operations", "PilotApproval")
    PilotTrial = apps.get_model("operations", "PilotTrial")
    roles = ("operations", "quality_safety", "engineering_it", "product_owner")
    PilotApproval.objects.bulk_create(
        [
            PilotApproval(trial_id=trial_id, reviewer_role=role)
            for trial_id in PilotTrial.objects.values_list("id", flat=True)
            for role in roles
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0012_pilot_trial_evidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer_role",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("quality_safety", "Quality/Safety"),
                            ("engineering_it", "Engineering/IT"),
                            ("product_owner", "Product Owner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pilot_approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="operations.pilottrial",
                    ),
                ),
            ],
            options={
                "ordering": ("reviewer_role",),
                "indexes": [
                    models.Index(
                        fields=["trial", "decision"],
                        name="operations__trial_i_bed952_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trial", "reviewer_role"),
                        name="unique_pilot_trial_reviewer_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PilotFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer_role",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("quality_safety", "Quality/Safety"),
                            ("engineering_it", "Engineering/IT"),
                            ("product_owner", "Product Owner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("usability", "Usability"),
                            ("workflow", "Workflow"),
                            ("safety_quality", "Safety/Quality"),
                            ("technical", "Technical"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("concern", "Concern"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pilot_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback",
                        to="operations.pilottrial",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["trial", "created_at"],
                        name="operations__trial_i_f5851e_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_pending_pilot_approvals, migrations.RunPython.noop),
    ]
