# Generated by Django 5.2.17 on 2026-09-11 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_pilotapproval_pilotfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlanBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('block_type', models.CharField(choices=[('production', 'Production'), ('break', 'Break')], max_length=12)),
                ('planned_start_at', models.DateTimeField()),
                ('planned_end_at', models.DateTimeField()),
                ('product_code', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=150)),
                ('target_units_per_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('break_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_plan_blocks', to='operations.teamleaderassignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_plan_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('assignment__date', 'planned_start_at', 'sequence_number'),
            },
        ),
        migrations.CreateModel(
            name='BreakOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('returned', 'Returned'), ('checks_complete', 'Checks Complete'), ('recovered', 'Recovered'), ('declined', 'Declined')], default='suggested', max_length=20)),
                ('fault_at', models.DateTimeField()),
                ('suggested_start_at', models.DateTimeField()),
                ('expected_return_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('checks_completed_at', models.DateTimeField(blank=True, null=True)),
                ('run_resumed_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_notes', models.TextField(blank=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_opportunities', to='operations.teamleaderassignment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_break_opportunities', to=settings.AUTH_USER_MODEL)),
                ('declined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declined_break_opportunities', to=settings.AUTH_USER_MODEL)),
                ('source_update', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='break_opportunity', to='operations.hourlylineupdate')),
                ('break_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_opportunities', to='operations.dailyplanblock')),
            ],
            options={
                'ordering': ('status', '-fault_at'),
            },
        ),
        migrations.AddIndex(
            model_name='dailyplanblock',
            index=models.Index(fields=['assignment', 'planned_start_at'], name='operations__assignm_ed7a40_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplanblock',
            index=models.Index(fields=['block_type', 'planned_start_at'], name='operations__block_t_07ec3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyplanblock',
            constraint=models.UniqueConstraint(fields=('assignment', 'sequence_number'), name='unique_assignment_daily_plan_sequence'),
        ),
        migrations.AddConstraint(
            model_name='dailyplanblock',
            constraint=models.UniqueConstraint(condition=models.Q(('block_type', 'break')), fields=('assignment', 'break_number'), name='unique_assignment_break_number'),
        ),
        migrations.AddIndex(
            model_name='breakopportunity',
            index=models.Index(fields=['assignment', 'status'], name='operations__assignm_5843cd_idx'),
        ),
        migrations.AddIndex(
            model_name='breakopportunity',
            index=models.Index(fields=['break_block', 'status'], name='operations__break_b_42c202_idx'),
        ),
    ]
